# Generated by Django 5.1.2 on 2025-03-20 21:07

import apps.discussions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('technical', 'Technical'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionmedia',
            name='file',
            field=models.FileField(upload_to=apps.discussions.models.question_file_path),
        ),
        migrations.AlterField(
            model_name='questionmedia',
            name='file_type',
            field=models.CharField(max_length=100),
        ),
    ]
