# Generated by Django 5.1.2 on 2025-03-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='moderation_categories',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='moderation_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='answer',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='answer',
            name='similarity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
