# Generated by Django 5.1.2 on 2025-03-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0004_answer_is_duplicate_answer_moderation_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='original_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
