# Generated by Django 5.1.2 on 2025-03-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0005_answer_ai_analysis_answer_original_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('huggingface', 'Hugging Face')], default='openai', max_length=20)),
                ('openai_api_key', models.CharField(blank=True, max_length=255)),
                ('huggingface_api_key', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Setting',
                'verbose_name_plural': 'AI Settings',
            },
        ),
    ]
