# Generated by Django 5.1.2 on 2025-04-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0006_aisettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aisettings',
            options={},
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='huggingface_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('huggingface', 'Hugging Face')], max_length=20),
        ),
    ]
